name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - run: pacman -Sy --needed --noconfirm base-devel git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: useradd -G wheel archie
      - run: mkdir -v /etc/sudoers.d || true
      - run: echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel.conf
      - run: chown -vR archie /__w/archrepo/archrepo
      - run: git config --global --add safe.directory /__w/archrepo/archrepo
      - run: git submodule foreach su archie -c 'makepkg -s'
