name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - run: pacman -Sy --needed --noconfirm base-devel git
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sed -i '/E_ROOT/d' /usr/bin/makepkg
      - run: git config --global --add safe.directory /__w/archrepo/archrepo
      - run: git submodule foreach makepkg -s
